# Generated by Django 4.2 on 2023-05-05 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='big_maximum',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=list, size=None),
        ),
        migrations.AddField(
            model_name='data',
            name='small_maximum',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='button',
            field=models.CharField(default='a', max_length=3),
        ),
    ]
